import = [
  "~/.config/alacritty/onedark.toml"
]

[window]
option_as_alt = "Both"
dimensions = { columns = 180, lines = 60 }

[font]
size = 12.5

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
