theme = "onedark"

[editor]
bufferline = "always"
line-number = "relative"
cursorline = true
color-modes = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.soft-wrap]
enable = true

[keys.insert]
j = { k = "normal_mode" }

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]
