[[language]]
name = "templ"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
# formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "go"
# go install golang.org/x/tools/cmd/goimports@latest
formatter = { command = "goimports" }

[[language]]
name = "c"
language-id = "c"
scope = "source.c"
auto-format = true
file-types = ["c", "h"]
language-servers = ["clangd"]
